//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLSOCdesktop.ServiceReference4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Modulesc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Modulesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LecnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lecname {
            get {
                return this.LecnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LecnameField, value) != true)) {
                    this.LecnameField = value;
                    this.RaisePropertyChanged("Lecname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modcode {
            get {
                return this.ModcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModcodeField, value) != true)) {
                    this.ModcodeField = value;
                    this.RaisePropertyChanged("Modcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modname {
            get {
                return this.ModnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModnameField, value) != true)) {
                    this.ModnameField = value;
                    this.RaisePropertyChanged("Modname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lechallsc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Lechallsc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LechallcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumstuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lechallcode {
            get {
                return this.LechallcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LechallcodeField, value) != true)) {
                    this.LechallcodeField = value;
                    this.RaisePropertyChanged("Lechallcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numstu {
            get {
                return this.NumstuField;
            }
            set {
                if ((object.ReferenceEquals(this.NumstuField, value) != true)) {
                    this.NumstuField = value;
                    this.RaisePropertyChanged("Numstu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Labsc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Labsc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumstuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Labcode {
            get {
                return this.LabcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LabcodeField, value) != true)) {
                    this.LabcodeField = value;
                    this.RaisePropertyChanged("Labcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numstu {
            get {
                return this.NumstuField;
            }
            set {
                if ((object.ReferenceEquals(this.NumstuField, value) != true)) {
                    this.NumstuField = value;
                    this.RaisePropertyChanged("Numstu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timetablesc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Timetablesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LechallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LecnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch {
            get {
                return this.BatchField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchField, value) != true)) {
                    this.BatchField = value;
                    this.RaisePropertyChanged("Batch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lab {
            get {
                return this.LabField;
            }
            set {
                if ((object.ReferenceEquals(this.LabField, value) != true)) {
                    this.LabField = value;
                    this.RaisePropertyChanged("Lab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lechall {
            get {
                return this.LechallField;
            }
            set {
                if ((object.ReferenceEquals(this.LechallField, value) != true)) {
                    this.LechallField = value;
                    this.RaisePropertyChanged("Lechall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lecname {
            get {
                return this.LecnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LecnameField, value) != true)) {
                    this.LecnameField = value;
                    this.RaisePropertyChanged("Lecname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modcode {
            get {
                return this.ModcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModcodeField, value) != true)) {
                    this.ModcodeField = value;
                    this.RaisePropertyChanged("Modcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lecturersc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Lecturersc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdtwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModulethreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuletwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adone {
            get {
                return this.AdoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AdoneField, value) != true)) {
                    this.AdoneField = value;
                    this.RaisePropertyChanged("Adone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adtwo {
            get {
                return this.AdtwoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdtwoField, value) != true)) {
                    this.AdtwoField = value;
                    this.RaisePropertyChanged("Adtwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jdate {
            get {
                return this.JdateField;
            }
            set {
                if ((object.ReferenceEquals(this.JdateField, value) != true)) {
                    this.JdateField = value;
                    this.RaisePropertyChanged("Jdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname {
            get {
                return this.LnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LnameField, value) != true)) {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moduleone {
            get {
                return this.ModuleoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleoneField, value) != true)) {
                    this.ModuleoneField = value;
                    this.RaisePropertyChanged("Moduleone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modulethree {
            get {
                return this.ModulethreeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModulethreeField, value) != true)) {
                    this.ModulethreeField = value;
                    this.RaisePropertyChanged("Modulethree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moduletwo {
            get {
                return this.ModuletwoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuletwoField, value) != true)) {
                    this.ModuletwoField = value;
                    this.RaisePropertyChanged("Moduletwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rdate {
            get {
                return this.RdateField;
            }
            set {
                if ((object.ReferenceEquals(this.RdateField, value) != true)) {
                    this.RdateField = value;
                    this.RaisePropertyChanged("Rdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Studentsc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Studentsc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdtwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ByearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adone {
            get {
                return this.AdoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AdoneField, value) != true)) {
                    this.AdoneField = value;
                    this.RaisePropertyChanged("Adone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adtwo {
            get {
                return this.AdtwoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdtwoField, value) != true)) {
                    this.AdtwoField = value;
                    this.RaisePropertyChanged("Adtwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Byear {
            get {
                return this.ByearField;
            }
            set {
                if ((object.ReferenceEquals(this.ByearField, value) != true)) {
                    this.ByearField = value;
                    this.RaisePropertyChanged("Byear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jdate {
            get {
                return this.JdateField;
            }
            set {
                if ((object.ReferenceEquals(this.JdateField, value) != true)) {
                    this.JdateField = value;
                    this.RaisePropertyChanged("Jdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname {
            get {
                return this.LnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LnameField, value) != true)) {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nic {
            get {
                return this.NicField;
            }
            set {
                if ((object.ReferenceEquals(this.NicField, value) != true)) {
                    this.NicField = value;
                    this.RaisePropertyChanged("Nic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Feedbacksc", Namespace="http://schemas.datacontract.org/2004/07/SLSOCserver")]
    [System.SerializableAttribute()]
    public partial class Feedbacksc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feedback {
            get {
                return this.FeedbackField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackField, value) != true)) {
                    this.FeedbackField = value;
                    this.RaisePropertyChanged("Feedback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modcode {
            get {
                return this.ModcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModcodeField, value) != true)) {
                    this.ModcodeField = value;
                    this.RaisePropertyChanged("Modcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService4")]
    public interface IService4 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddModules", ReplyAction="http://tempuri.org/IService4/AddModulesResponse")]
        int AddModules(SLSOCdesktop.ServiceReference4.Modulesc md);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddModules", ReplyAction="http://tempuri.org/IService4/AddModulesResponse")]
        System.Threading.Tasks.Task<int> AddModulesAsync(SLSOCdesktop.ServiceReference4.Modulesc md);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchModules", ReplyAction="http://tempuri.org/IService4/SearchModulesResponse")]
        SLSOCdesktop.ServiceReference4.Modulesc SearchModules(string Modcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchModules", ReplyAction="http://tempuri.org/IService4/SearchModulesResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Modulesc> SearchModulesAsync(string Modcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComModules", ReplyAction="http://tempuri.org/IService4/GetComModulesResponse")]
        SLSOCdesktop.ServiceReference4.Modulesc[] GetComModules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComModules", ReplyAction="http://tempuri.org/IService4/GetComModulesResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Modulesc[]> GetComModulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/UpdateComModules", ReplyAction="http://tempuri.org/IService4/UpdateComModulesResponse")]
        int UpdateComModules(SLSOCdesktop.ServiceReference4.Modulesc cmu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/UpdateComModules", ReplyAction="http://tempuri.org/IService4/UpdateComModulesResponse")]
        System.Threading.Tasks.Task<int> UpdateComModulesAsync(SLSOCdesktop.ServiceReference4.Modulesc cmu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/DeleteComModules", ReplyAction="http://tempuri.org/IService4/DeleteComModulesResponse")]
        int DeleteComModules(SLSOCdesktop.ServiceReference4.Modulesc cmdel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/DeleteComModules", ReplyAction="http://tempuri.org/IService4/DeleteComModulesResponse")]
        System.Threading.Tasks.Task<int> DeleteComModulesAsync(SLSOCdesktop.ServiceReference4.Modulesc cmdel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddLecHalls", ReplyAction="http://tempuri.org/IService4/AddLecHallsResponse")]
        int AddLecHalls(SLSOCdesktop.ServiceReference4.Lechallsc lhd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddLecHalls", ReplyAction="http://tempuri.org/IService4/AddLecHallsResponse")]
        System.Threading.Tasks.Task<int> AddLecHallsAsync(SLSOCdesktop.ServiceReference4.Lechallsc lhd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchLecHalls", ReplyAction="http://tempuri.org/IService4/SearchLecHallsResponse")]
        SLSOCdesktop.ServiceReference4.Lechallsc SearchLecHalls(string Lechallcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchLecHalls", ReplyAction="http://tempuri.org/IService4/SearchLecHallsResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lechallsc> SearchLecHallsAsync(string Lechallcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComLecHalls", ReplyAction="http://tempuri.org/IService4/GetComLecHallsResponse")]
        SLSOCdesktop.ServiceReference4.Lechallsc[] GetComLecHalls();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComLecHalls", ReplyAction="http://tempuri.org/IService4/GetComLecHallsResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lechallsc[]> GetComLecHallsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/UpdateComlecHalls", ReplyAction="http://tempuri.org/IService4/UpdateComlecHallsResponse")]
        int UpdateComlecHalls(SLSOCdesktop.ServiceReference4.Lechallsc clhu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/UpdateComlecHalls", ReplyAction="http://tempuri.org/IService4/UpdateComlecHallsResponse")]
        System.Threading.Tasks.Task<int> UpdateComlecHallsAsync(SLSOCdesktop.ServiceReference4.Lechallsc clhu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/DeleteComLecHalls", ReplyAction="http://tempuri.org/IService4/DeleteComLecHallsResponse")]
        int DeleteComLecHalls(SLSOCdesktop.ServiceReference4.Lechallsc clhdel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/DeleteComLecHalls", ReplyAction="http://tempuri.org/IService4/DeleteComLecHallsResponse")]
        System.Threading.Tasks.Task<int> DeleteComLecHallsAsync(SLSOCdesktop.ServiceReference4.Lechallsc clhdel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddLabs", ReplyAction="http://tempuri.org/IService4/AddLabsResponse")]
        int AddLabs(SLSOCdesktop.ServiceReference4.Labsc lbd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddLabs", ReplyAction="http://tempuri.org/IService4/AddLabsResponse")]
        System.Threading.Tasks.Task<int> AddLabsAsync(SLSOCdesktop.ServiceReference4.Labsc lbd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchLabs", ReplyAction="http://tempuri.org/IService4/SearchLabsResponse")]
        SLSOCdesktop.ServiceReference4.Labsc SearchLabs(string Labcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchLabs", ReplyAction="http://tempuri.org/IService4/SearchLabsResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Labsc> SearchLabsAsync(string Labcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComLabs", ReplyAction="http://tempuri.org/IService4/GetComLabsResponse")]
        SLSOCdesktop.ServiceReference4.Labsc[] GetComLabs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComLabs", ReplyAction="http://tempuri.org/IService4/GetComLabsResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Labsc[]> GetComLabsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/UpdateComLabs", ReplyAction="http://tempuri.org/IService4/UpdateComLabsResponse")]
        int UpdateComLabs(SLSOCdesktop.ServiceReference4.Labsc clbu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/UpdateComLabs", ReplyAction="http://tempuri.org/IService4/UpdateComLabsResponse")]
        System.Threading.Tasks.Task<int> UpdateComLabsAsync(SLSOCdesktop.ServiceReference4.Labsc clbu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/DeleteComLabs", ReplyAction="http://tempuri.org/IService4/DeleteComLabsResponse")]
        int DeleteComLabs(SLSOCdesktop.ServiceReference4.Labsc clbdel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/DeleteComLabs", ReplyAction="http://tempuri.org/IService4/DeleteComLabsResponse")]
        System.Threading.Tasks.Task<int> DeleteComLabsAsync(SLSOCdesktop.ServiceReference4.Labsc clbdel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddTimetables", ReplyAction="http://tempuri.org/IService4/AddTimetablesResponse")]
        int AddTimetables(SLSOCdesktop.ServiceReference4.Timetablesc td);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/AddTimetables", ReplyAction="http://tempuri.org/IService4/AddTimetablesResponse")]
        System.Threading.Tasks.Task<int> AddTimetablesAsync(SLSOCdesktop.ServiceReference4.Timetablesc td);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComTimetables", ReplyAction="http://tempuri.org/IService4/GetComTimetablesResponse")]
        SLSOCdesktop.ServiceReference4.Timetablesc[] GetComTimetables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetComTimetables", ReplyAction="http://tempuri.org/IService4/GetComTimetablesResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Timetablesc[]> GetComTimetablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetEngineeringLecturers", ReplyAction="http://tempuri.org/IService4/GetEngineeringLecturersResponse")]
        SLSOCdesktop.ServiceReference4.Lecturersc[] GetEngineeringLecturers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetEngineeringLecturers", ReplyAction="http://tempuri.org/IService4/GetEngineeringLecturersResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lecturersc[]> GetEngineeringLecturersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetEngineeringStudents", ReplyAction="http://tempuri.org/IService4/GetEngineeringStudentsResponse")]
        SLSOCdesktop.ServiceReference4.Studentsc[] GetEngineeringStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetEngineeringStudents", ReplyAction="http://tempuri.org/IService4/GetEngineeringStudentsResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Studentsc[]> GetEngineeringStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchLecturers", ReplyAction="http://tempuri.org/IService4/SearchLecturersResponse")]
        SLSOCdesktop.ServiceReference4.Lecturersc SearchLecturers(SLSOCdesktop.ServiceReference4.Lecturersc ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchLecturers", ReplyAction="http://tempuri.org/IService4/SearchLecturersResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lecturersc> SearchLecturersAsync(SLSOCdesktop.ServiceReference4.Lecturersc ls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchStudents", ReplyAction="http://tempuri.org/IService4/SearchStudentsResponse")]
        SLSOCdesktop.ServiceReference4.Studentsc SearchStudents(SLSOCdesktop.ServiceReference4.Studentsc ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/SearchStudents", ReplyAction="http://tempuri.org/IService4/SearchStudentsResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Studentsc> SearchStudentsAsync(SLSOCdesktop.ServiceReference4.Studentsc ss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetEngFeedbacks", ReplyAction="http://tempuri.org/IService4/GetEngFeedbacksResponse")]
        SLSOCdesktop.ServiceReference4.Feedbacksc[] GetEngFeedbacks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/GetEngFeedbacks", ReplyAction="http://tempuri.org/IService4/GetEngFeedbacksResponse")]
        System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Feedbacksc[]> GetEngFeedbacksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService4Channel : SLSOCdesktop.ServiceReference4.IService4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service4Client : System.ServiceModel.ClientBase<SLSOCdesktop.ServiceReference4.IService4>, SLSOCdesktop.ServiceReference4.IService4 {
        
        public Service4Client() {
        }
        
        public Service4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddModules(SLSOCdesktop.ServiceReference4.Modulesc md) {
            return base.Channel.AddModules(md);
        }
        
        public System.Threading.Tasks.Task<int> AddModulesAsync(SLSOCdesktop.ServiceReference4.Modulesc md) {
            return base.Channel.AddModulesAsync(md);
        }
        
        public SLSOCdesktop.ServiceReference4.Modulesc SearchModules(string Modcode) {
            return base.Channel.SearchModules(Modcode);
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Modulesc> SearchModulesAsync(string Modcode) {
            return base.Channel.SearchModulesAsync(Modcode);
        }
        
        public SLSOCdesktop.ServiceReference4.Modulesc[] GetComModules() {
            return base.Channel.GetComModules();
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Modulesc[]> GetComModulesAsync() {
            return base.Channel.GetComModulesAsync();
        }
        
        public int UpdateComModules(SLSOCdesktop.ServiceReference4.Modulesc cmu) {
            return base.Channel.UpdateComModules(cmu);
        }
        
        public System.Threading.Tasks.Task<int> UpdateComModulesAsync(SLSOCdesktop.ServiceReference4.Modulesc cmu) {
            return base.Channel.UpdateComModulesAsync(cmu);
        }
        
        public int DeleteComModules(SLSOCdesktop.ServiceReference4.Modulesc cmdel) {
            return base.Channel.DeleteComModules(cmdel);
        }
        
        public System.Threading.Tasks.Task<int> DeleteComModulesAsync(SLSOCdesktop.ServiceReference4.Modulesc cmdel) {
            return base.Channel.DeleteComModulesAsync(cmdel);
        }
        
        public int AddLecHalls(SLSOCdesktop.ServiceReference4.Lechallsc lhd) {
            return base.Channel.AddLecHalls(lhd);
        }
        
        public System.Threading.Tasks.Task<int> AddLecHallsAsync(SLSOCdesktop.ServiceReference4.Lechallsc lhd) {
            return base.Channel.AddLecHallsAsync(lhd);
        }
        
        public SLSOCdesktop.ServiceReference4.Lechallsc SearchLecHalls(string Lechallcode) {
            return base.Channel.SearchLecHalls(Lechallcode);
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lechallsc> SearchLecHallsAsync(string Lechallcode) {
            return base.Channel.SearchLecHallsAsync(Lechallcode);
        }
        
        public SLSOCdesktop.ServiceReference4.Lechallsc[] GetComLecHalls() {
            return base.Channel.GetComLecHalls();
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lechallsc[]> GetComLecHallsAsync() {
            return base.Channel.GetComLecHallsAsync();
        }
        
        public int UpdateComlecHalls(SLSOCdesktop.ServiceReference4.Lechallsc clhu) {
            return base.Channel.UpdateComlecHalls(clhu);
        }
        
        public System.Threading.Tasks.Task<int> UpdateComlecHallsAsync(SLSOCdesktop.ServiceReference4.Lechallsc clhu) {
            return base.Channel.UpdateComlecHallsAsync(clhu);
        }
        
        public int DeleteComLecHalls(SLSOCdesktop.ServiceReference4.Lechallsc clhdel) {
            return base.Channel.DeleteComLecHalls(clhdel);
        }
        
        public System.Threading.Tasks.Task<int> DeleteComLecHallsAsync(SLSOCdesktop.ServiceReference4.Lechallsc clhdel) {
            return base.Channel.DeleteComLecHallsAsync(clhdel);
        }
        
        public int AddLabs(SLSOCdesktop.ServiceReference4.Labsc lbd) {
            return base.Channel.AddLabs(lbd);
        }
        
        public System.Threading.Tasks.Task<int> AddLabsAsync(SLSOCdesktop.ServiceReference4.Labsc lbd) {
            return base.Channel.AddLabsAsync(lbd);
        }
        
        public SLSOCdesktop.ServiceReference4.Labsc SearchLabs(string Labcode) {
            return base.Channel.SearchLabs(Labcode);
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Labsc> SearchLabsAsync(string Labcode) {
            return base.Channel.SearchLabsAsync(Labcode);
        }
        
        public SLSOCdesktop.ServiceReference4.Labsc[] GetComLabs() {
            return base.Channel.GetComLabs();
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Labsc[]> GetComLabsAsync() {
            return base.Channel.GetComLabsAsync();
        }
        
        public int UpdateComLabs(SLSOCdesktop.ServiceReference4.Labsc clbu) {
            return base.Channel.UpdateComLabs(clbu);
        }
        
        public System.Threading.Tasks.Task<int> UpdateComLabsAsync(SLSOCdesktop.ServiceReference4.Labsc clbu) {
            return base.Channel.UpdateComLabsAsync(clbu);
        }
        
        public int DeleteComLabs(SLSOCdesktop.ServiceReference4.Labsc clbdel) {
            return base.Channel.DeleteComLabs(clbdel);
        }
        
        public System.Threading.Tasks.Task<int> DeleteComLabsAsync(SLSOCdesktop.ServiceReference4.Labsc clbdel) {
            return base.Channel.DeleteComLabsAsync(clbdel);
        }
        
        public int AddTimetables(SLSOCdesktop.ServiceReference4.Timetablesc td) {
            return base.Channel.AddTimetables(td);
        }
        
        public System.Threading.Tasks.Task<int> AddTimetablesAsync(SLSOCdesktop.ServiceReference4.Timetablesc td) {
            return base.Channel.AddTimetablesAsync(td);
        }
        
        public SLSOCdesktop.ServiceReference4.Timetablesc[] GetComTimetables() {
            return base.Channel.GetComTimetables();
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Timetablesc[]> GetComTimetablesAsync() {
            return base.Channel.GetComTimetablesAsync();
        }
        
        public SLSOCdesktop.ServiceReference4.Lecturersc[] GetEngineeringLecturers() {
            return base.Channel.GetEngineeringLecturers();
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lecturersc[]> GetEngineeringLecturersAsync() {
            return base.Channel.GetEngineeringLecturersAsync();
        }
        
        public SLSOCdesktop.ServiceReference4.Studentsc[] GetEngineeringStudents() {
            return base.Channel.GetEngineeringStudents();
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Studentsc[]> GetEngineeringStudentsAsync() {
            return base.Channel.GetEngineeringStudentsAsync();
        }
        
        public SLSOCdesktop.ServiceReference4.Lecturersc SearchLecturers(SLSOCdesktop.ServiceReference4.Lecturersc ls) {
            return base.Channel.SearchLecturers(ls);
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Lecturersc> SearchLecturersAsync(SLSOCdesktop.ServiceReference4.Lecturersc ls) {
            return base.Channel.SearchLecturersAsync(ls);
        }
        
        public SLSOCdesktop.ServiceReference4.Studentsc SearchStudents(SLSOCdesktop.ServiceReference4.Studentsc ss) {
            return base.Channel.SearchStudents(ss);
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Studentsc> SearchStudentsAsync(SLSOCdesktop.ServiceReference4.Studentsc ss) {
            return base.Channel.SearchStudentsAsync(ss);
        }
        
        public SLSOCdesktop.ServiceReference4.Feedbacksc[] GetEngFeedbacks() {
            return base.Channel.GetEngFeedbacks();
        }
        
        public System.Threading.Tasks.Task<SLSOCdesktop.ServiceReference4.Feedbacksc[]> GetEngFeedbacksAsync() {
            return base.Channel.GetEngFeedbacksAsync();
        }
    }
}
